name: wf_call_sf_terraform_matrix

on:
  push:
    branches:
      - dev
      - qut
      - main
    paths: 
      - 'terraform_infra/**'
  workflow_dispatch:

jobs:
  Generate-Workflows:
    runs-on: ubuntu-latest
    outputs:
      changedFoldersMatrix: ${{ steps.generate-matrix.outputs.changedFoldersMatrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to ensure HEAD~1 is available

      - name: Generate matrix
        id: generate-matrix
        run: |
          echo "Generating changed folders matrix..."
          changed_folders=$(git diff --name-only HEAD~1 HEAD | grep 'terraform_infra/' | sed 's|/[^/]*$||' | sort -u)
          echo "Changed folders: $changed_folders"
          matrix_json=$(echo "$changed_folders" | jq -R -s -c 'split("\n")[:-1] | map(select(length > 0)) | map({"folderName": .})')
          echo "Matrix JSON: $matrix_json"
          echo "changedFoldersMatrix=$matrix_json" >> $GITHUB_OUTPUT

  call-terraform-deployment:
    needs: Generate-Workflows
    if: needs.Generate-Workflows.outputs.changedFoldersMatrix != '[]' && needs.Generate-Workflows.outputs.changedFoldersMatrix != ''
    strategy:
      matrix: 
        include: ${{ fromJSON(needs.Generate-Workflows.outputs.changedFoldersMatrix) }}
    uses: ./.github/workflows/wf_sf_terraform_deploy.yml
    with:
      environment: ${{ matrix.folderName }}
      path: ${{ matrix.folderName }}
    secrets: inherit
