name: wf_call_sf_terraform_matrix

on:
  push:
    branches:
      - dev
      - qut
      - main
    paths: 
      - 'terraform_infra/**'
  workflow_dispatch:

jobs:
  Generate-Workflows:
    runs-on: ubuntu-latest
    outputs:
      changedFoldersMatrix: ${{ steps.generate-matrix.outputs.changedFoldersMatrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to ensure HEAD~1 is available

      - name: Generate matrix
        id: generate-matrix
        run: |
          changed_folders=$(git diff --name-only HEAD~1 HEAD | grep 'terraform_infra/' | sed 's|/[^/]*$||' | sort -u | jq -R -s -c 'split("\n")[:-1] | map({"folderName": .})')
          echo "changedFoldersMatrix=$changed_folders" >> $GITHUB_OUTPUT

  deploy:
    if: needs.Generate-Workflows.outputs.changedFoldersMatrix != '[]' && needs.Generate-Workflows.outputs.changedFoldersMatrix != ''
    needs: 
      - Generate-Workflows
    strategy:
      matrix: ${{ fromJSON(needs.Generate-Workflows.outputs.changedFoldersMatrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract Environment from Folder Name
        id: extract-env
        run: |
          folderName="${{ matrix.folderName }}"
          environment=$(echo "$folderName" | awk -F'_' '{print tolower($NF)}')
          echo "environment=$environment" >> $GITHUB_ENV

      - name: Call Terraform Deployment
        uses: ./.github/workflows/wf_sf_terraform_deploy.yml
        with:
          environment: ${{ env.environment }}
          path: ${{ matrix.folderName }}
          secrets: inherit
