name: wf_call_sf_terraform

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy_dev:
    if: github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/wf_sf_terraform_deploy.yml
    with:
      environment: dev
    secrets: inherit

  deploy_qut:
    if: github.ref == 'refs/heads/qut'
    uses: ./.github/workflows/wf_sf_terraform_deploy.yml
    with:
      environment: qut
    secrets: inherit

  deploy_prd:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/wf_sf_terraform_deploy.yml
    with:
      environment: prd
    secrets: inherit
