name: wf_Terraform
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    env:
      # Snowflake Variables
      TF_VAR_snowflake_account:  ${{ secrets.SNOWFLAKE_ACCOUNT }}
      TF_VAR_snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
      TF_VAR_snowflake_username: ${{ secrets.SNOWFLAKE_USERNAME }}
      TF_VAR_snowflake_role: ${{ secrets.SNOWFLAKE_ROLE }}

      # Azure Authentication
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.11

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=plan.out -lock=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -lock=false
