name: wf_Terraform
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    env:
      TF_VAR_snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      TF_VAR_snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
      TF_VAR_snowflake_username: ${{ secrets.SNOWFLAKE_USERNAME }}
      TF_VAR_snowflake_role: ${{ secrets.SNOWFLAKE_ROLE }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -refresh-only

      - name: Terraform Apply
        run: terraform apply -auto-approve
